# Generated by Django 4.0.5 on 2022-07-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0002_people_alter_transaction_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=100)),
                ('reference', models.ManyToManyField(blank=True, related_name='member', to='general_ledger.people')),
            ],
        ),
    ]
